/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness + a cheap store summary, for the frontend's plumbing check.
         *
         *     Run discovery is best-effort: a malformed/absent store must never 500 the
         *     health probe, so discovery failures degrade to ``runs: 0`` rather than
         *     propagating (the broad guard is deliberate and scoped to this probe).
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Every discoverable run, newest first by last-written chain mtime.
         */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description One run's metadata, schema, and authoritative verdict.
         */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/posterior": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Posterior
         * @description Doc-labelled posterior summary (the forest-plot payload). Params are in
         *     the model's estimated order; a run with no draws yet returns ``params=[]``
         *     and ``n_tail=0`` rather than erroring.
         */
        get: operations["get_posterior_api_runs__run_id__posterior_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/draws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Draws
         * @description Row-aligned post-warmup draws (plus marginal prior samples) for the
         *     marginal densities and the pair plot. Pooled across chains, thinned to
         *     ``max_draws``; ``params`` in estimated order. A run with no draws yet returns
         *     empty columns and ``n_draws=0`` (priors are still sampled).
         */
        get: operations["get_draws_api_runs__run_id__draws_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Source
         * @description The fit's sources: the highlighted ``.camdl`` model (read live from its
         *     recorded path) and the mirrored ``fit.toml`` (always in the run store).
         */
        get: operations["get_source_api_runs__run_id__source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/predictive/{stream}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Predictive
         * @description One stream's posterior-predictive ribbons (``camdl fit predict`` output)
         *     plus the observed series. 404 if the stream has no predictive artifact.
         */
        get: operations["get_predictive_api_runs__run_id__predictive__stream__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/quantity-series/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quantity Series
         * @description One series quantity's banded trajectory (a ribbon). 404 if the run has no
         *     such series quantity in its manifest, or its TSV is missing.
         */
        get: operations["get_quantity_series_api_runs__run_id__quantity_series__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/quantity-scalars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quantity Scalars
         * @description Every scalar quantity, one row per stratum cell — the quantities table.
         *     Manifest-driven (stale orphan TSVs are ignored).
         */
        get: operations["get_quantity_scalars_api_runs__run_id__quantity_scalars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Traces
         * @description Per-parameter, per-chain iteration traces (thinned) for the trace grid.
         *     Includes the estimated coordinates plus any present objective aux columns
         *     (``log_posterior`` / ``log_likelihood``) — the first thing to eyeball for
         *     mixing.
         */
        get: operations["get_traces_api_runs__run_id__traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Diagnostics
         * @description Convergence diagnostics: camdl's authoritative verdict (findings) and
         *     R̂/ESS where a stage summary exists, else the watcher's live arviz estimate;
         *     plus per-chain mixing (acceptance / trajectory renewal) and the PMMH MAP.
         */
        get: operations["get_diagnostics_api_runs__run_id__diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare
         * @description Prequential model comparison via the authoritative ``camdl compare``.
         *
         *     Resolves each run's ``prequential.json``, shells out (single source of truth
         *     for the elpd / Δelpd math and the evidence scale), and projects the result.
         *     Runs lacking a score artifact are dropped (reported in
         *     ``missing_prequential``). When the surviving models were scored on different
         *     horizons, camdl's commensurability guard trips: Δ columns come back ``None``
         *     and ``commensurable`` is false (the caller may still pass
         *     ``allow_mismatched_horizon`` to acknowledge it explicitly).
         */
        get: operations["compare_api_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChainMixing
         * @description Per-chain mixing metric — MH/PMMH acceptance rate or PGAS trajectory
         *     renewal — with an optional healthy band ``(lo, hi)``.
         */
        ChainMixing: {
            /** Label */
            label: string;
            /** Values */
            values: number[];
            /** Band */
            band?: [
                number,
                number
            ] | null;
        };
        /**
         * CompareResponse
         * @description A prequential model comparison. ``commensurable`` is false when the models
         *     were scored on different horizons (``T_score`` mismatch) — Δ columns are then
         *     meaningless and arrive ``None``. ``notes`` carries camdl's advisories (e.g.
         *     the in-sample / plug-in optimism caveat). ``missing_prequential`` lists
         *     requested runs that had no score artifact and were dropped. Rows are in
         *     camdl's order: ascending Δelpd, best-supported last.
         */
        CompareResponse: {
            /** Baseline */
            baseline: string;
            /** Metrics */
            metrics: string[];
            /** Commensurable */
            commensurable: boolean;
            /**
             * Notes
             * @default []
             */
            notes: string[];
            /** Rows */
            rows: components["schemas"]["CompareRow"][];
            /**
             * Missing Prequential
             * @default []
             */
            missing_prequential: string[];
        };
        /**
         * CompareRow
         * @description One model's prequential scores in a comparison, projected from ``camdl
         *     compare --format json``. Δ fields are ``None`` for the baseline row and when
         *     the models are not commensurable (``T_score`` mismatch). ``elpd`` is the
         *     summed out-of-sample log predictive density (higher = better); ``delta_elpd``
         *     is paired against the baseline with ``se_delta_elpd``; ``e_t = exp(Δelpd)`` is
         *     the terminal e-value / Bayes factor; ``evidence_label`` is the Jeffreys tier
         *     of ``delta_elpd_db`` (decibans).
         */
        CompareRow: {
            /** Run Id */
            run_id: string;
            /** Label */
            label: string;
            /** T Score */
            t_score: number;
            /** Elpd */
            elpd: number;
            /** Delta Elpd */
            delta_elpd?: number | null;
            /** Delta Elpd Db */
            delta_elpd_db?: number | null;
            /** Evidence Label */
            evidence_label?: string | null;
            /** E T */
            e_t?: number | null;
            /** Se Delta Elpd */
            se_delta_elpd?: number | null;
            /** Mean Crps */
            mean_crps?: number | null;
            /** Delta Mean Crps */
            delta_mean_crps?: number | null;
            /** Pit Cov90 */
            pit_cov90?: number | null;
            /**
             * Is Baseline
             * @default false
             */
            is_baseline: boolean;
            /**
             * Gap Is Real
             * @default false
             */
            gap_is_real: boolean;
            /**
             * Overconfident
             * @default false
             */
            overconfident: boolean;
        };
        /**
         * DiagnosticsResponse
         * @description The full convergence picture for a run: camdl's verdict (findings), a
         *     per-parameter R̂/ESS table, per-chain mixing, and the PMMH MAP if present.
         *     ``source`` is ``camdl`` when an authoritative stage summary backs R̂/ESS, else
         *     ``live`` (the watcher's arviz estimate while a run is still sampling).
         */
        DiagnosticsResponse: {
            /** Run Id */
            run_id: string;
            /** Warmup Pct */
            warmup_pct: number;
            /** Warmup Cutoff */
            warmup_cutoff: number;
            /** N Tail */
            n_tail: number;
            /** N Chains */
            n_chains: number;
            /** Stage */
            stage?: string | null;
            /** Source */
            source: string;
            /** Logpost Label */
            logpost_label: string;
            /** Findings */
            findings: components["schemas"]["FindingGroup"][];
            /** Params */
            params: components["schemas"]["ParamDiagnostic"][];
            mixing?: components["schemas"]["ChainMixing"] | null;
            /** Map Loglik */
            map_loglik?: number | null;
            /** Map Chain */
            map_chain?: number | null;
        };
        /**
         * DimensionInfo
         * @description One indexing dimension and its ordered levels (from the fit's ``schema``).
         */
        DimensionInfo: {
            /** Name */
            name: string;
            /** Levels */
            levels: string[];
        };
        /**
         * DrawsResponse
         * @description Row-aligned post-warmup posterior draws — the substrate for proper
         *     statistical graphics (marginal densities, the pair/corner plot). Row ``i`` is
         *     one joint sample: ``draws[param][i]`` for every param, drawn by chain
         *     ``chain[i]``. Pooled across chains and thinned to at most ``max_draws`` rows;
         *     every value is finite (non-finite rows are dropped to keep alignment).
         */
        DrawsResponse: {
            /** Run Id */
            run_id: string;
            /** Warmup Pct */
            warmup_pct: number;
            /** Warmup Cutoff */
            warmup_cutoff: number;
            /** N Draws */
            n_draws: number;
            /** Params */
            params: string[];
            /**
             * Objectives
             * @default []
             */
            objectives: string[];
            /** Chain */
            chain: number[];
            /** Draws */
            draws: {
                [key: string]: number[];
            };
            /**
             * Prior
             * @default {}
             */
            prior: {
                [key: string]: number[];
            };
            /**
             * Prior Density
             * @default {}
             */
            prior_density: {
                [key: string]: components["schemas"]["PriorCurve"];
            };
        };
        /**
         * FindingGroup
         * @description One ``kind`` of camdl diagnostic finding, collapsed to a single line.
         */
        FindingGroup: {
            /** Kind */
            kind: string;
            /** Severity */
            severity: string;
            /** Headline */
            headline: string;
            /** Params */
            params: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ObservedPoint
         * @description One observed value to overlay (``value`` is null where the series has a hole).
         */
        ObservedPoint: {
            /** Time */
            time: number;
            /**
             * Stratum
             * @default {}
             */
            stratum: {
                [key: string]: string;
            };
            /** Value */
            value?: number | null;
        };
        /**
         * ParamDiagnostic
         * @description One parameter's convergence/precision diagnostics. R̂ and combined ESS are
         *     camdl-authoritative when a stage summary exists, else the live arviz estimate;
         *     tail-ESS / MCSE / sep are the live estimate. ``ess_per_chain`` is camdl's
         *     per-chain breakdown (empty when unavailable). None where not estimable.
         */
        ParamDiagnostic: {
            /** Name */
            name: string;
            /** Symbol */
            symbol?: string | null;
            /** Rhat */
            rhat?: number | null;
            /** Ess Bulk */
            ess_bulk?: number | null;
            /** Ess Tail */
            ess_tail?: number | null;
            /** Mcse */
            mcse?: number | null;
            /** Mean */
            mean: number;
            /** Sd */
            sd: number;
            /** Sep */
            sep?: number | null;
            /**
             * Ess Per Chain
             * @default []
             */
            ess_per_chain: number[];
        };
        /**
         * ParamFamily
         * @description An indexed parameter family — a base name expanded per stratum, e.g.
         *     ``k_raw`` → ``[k_raw_Bo, k_raw_Bombali, …]``. The UI toggles these as a group.
         */
        ParamFamily: {
            /** Base */
            base: string;
            /** Members */
            members: string[];
        };
        /**
         * ParamGroups
         * @description Estimated coordinates partitioned for selection UIs: ungrouped ``scalars``
         *     plus indexed ``families`` (≥2 members). ``default_selection`` is the
         *     recommended visible set (scalars + hyperparameters; family leaves hidden) so
         *     a 20-parameter hierarchical fit doesn't open as a wall of panels.
         */
        ParamGroups: {
            /** Scalars */
            scalars: string[];
            /** Families */
            families: components["schemas"]["ParamFamily"][];
            /** Default Selection */
            default_selection: string[];
        };
        /**
         * ParamPosterior
         * @description One estimated coordinate, doc-labelled and summarized — the unit a forest
         *     plot draws: a point (``q50``) with an interval (``q05``…``q95``), a human
         *     label (``symbol`` / ``description`` / ``reference``), and its prior.
         */
        ParamPosterior: {
            /** Name */
            name: string;
            /** Symbol */
            symbol?: string | null;
            /** Description */
            description?: string | null;
            /** Reference */
            reference?: string | null;
            /** Source */
            source: string;
            /** Prior */
            prior?: string | null;
            /** Bounds */
            bounds?: [
                number,
                number
            ] | null;
            /** Mean */
            mean: number;
            /** Sd */
            sd: number;
            /** Q05 */
            q05: number;
            /** Q25 */
            q25: number;
            /** Q50 */
            q50: number;
            /** Q75 */
            q75: number;
            /** Q95 */
            q95: number;
            /** Rhat */
            rhat?: number | null;
            /** Ess */
            ess?: number | null;
        };
        /**
         * ParamTrace
         * @description One parameter's per-chain traces (estimated coordinate, or an objective
         *     like ``log_posterior``).
         */
        ParamTrace: {
            /** Param */
            param: string;
            /** Series */
            series: components["schemas"]["TraceSeries"][];
        };
        /**
         * PosteriorResponse
         * @description Doc-labelled posterior summary for one run — what the first frontend
         *     screen (the forest plot) consumes. ``params`` is in the model's estimated
         *     order; empty when the run has no draws yet.
         */
        PosteriorResponse: {
            /** Run Id */
            run_id: string;
            /** Warmup Pct */
            warmup_pct: number;
            /** Warmup Cutoff */
            warmup_cutoff: number;
            /** N Tail */
            n_tail: number;
            /** Params */
            params: components["schemas"]["ParamPosterior"][];
        };
        /**
         * PredictivePoint
         * @description One posterior-predictive ribbon point: quantiles at a time × stratum, for
         *     a given ``scenario`` × forecast ``horizon`` × ``treatment``. ``scenario`` is
         *     ``as_fitted`` for a scenario-less predict (and for the in-sample one_step
         *     rows, which are scenario-independent).
         */
        PredictivePoint: {
            /** Time */
            time: number;
            /**
             * Stratum
             * @default {}
             */
            stratum: {
                [key: string]: string;
            };
            /**
             * Scenario
             * @default as_fitted
             */
            scenario: string;
            /**
             * Horizon
             * @default
             */
            horizon: string;
            /**
             * Treatment
             * @default
             */
            treatment: string;
            /** Q05 */
            q05: number;
            /** Q25 */
            q25: number;
            /** Q50 */
            q50: number;
            /** Q75 */
            q75: number;
            /** Q95 */
            q95: number;
        };
        /**
         * PredictiveResponse
         * @description One stream's posterior-predictive ribbons + observed series. The frontend
         *     facets by ``stratum`` and filters by ``horizon`` (e.g. free_forward).
         */
        PredictiveResponse: {
            /** Run Id */
            run_id: string;
            /** Stream */
            stream: string;
            /** Index Dims */
            index_dims: string[];
            /** Scenarios */
            scenarios: string[];
            /** Horizons */
            horizons: string[];
            /** Treatments */
            treatments: string[];
            /** Predictive */
            predictive: components["schemas"]["PredictivePoint"][];
            /** Observed */
            observed: components["schemas"]["ObservedPoint"][];
        };
        /**
         * PriorCurve
         * @description A smooth analytic prior density: ``y`` evaluated at grid ``x`` (same length).
         */
        PriorCurve: {
            /** X */
            x: number[];
            /** Y */
            y: number[];
        };
        /**
         * ProgressInfo
         * @description camdl's per-run progress heartbeat (``progress.json``). ``phase`` /
         *     ``step`` / ``total`` are present only while running; ``reason`` only on
         *     failure; ``pct`` is the derived completion fraction (0–100) when step/total
         *     are known. ``updated_at`` is unix seconds — its freshness is the liveness
         *     signal.
         */
        ProgressInfo: {
            /** State */
            state: string;
            /** Phase */
            phase?: string | null;
            /** Step */
            step?: number | null;
            /** Total */
            total?: number | null;
            /** Pct */
            pct?: number | null;
            /** Reason */
            reason?: string | null;
            /** Updated At */
            updated_at?: number | null;
        };
        /**
         * QuantityBandPoint
         * @description One banded snapshot of a series quantity at a scenario × time × stratum.
         *     ``scenario`` is ``as_fitted`` for an old (scenario-less) sidecar.
         */
        QuantityBandPoint: {
            /**
             * Scenario
             * @default as_fitted
             */
            scenario: string;
            /** Time */
            time: number;
            /**
             * Stratum
             * @default {}
             */
            stratum: {
                [key: string]: string;
            };
            /** Q05 */
            q05: number;
            /** Q25 */
            q25: number;
            /** Q50 */
            q50: number;
            /** Q75 */
            q75: number;
            /** Q95 */
            q95: number;
        };
        /**
         * QuantityInfo
         * @description A generated quantity's identity + shape, from the manifest — enough to
         *     decide its rendering (``series`` → ribbon, ``scalar`` → table row) without
         *     reading its TSV. ``censorable`` flags a scalar whose reduction can fail to
         *     fire (a time-to-event), whose band is conditional on firing. ``unit`` is
         *     reserved upstream but currently always null.
         */
        QuantityInfo: {
            /** Name */
            name: string;
            /** Shape */
            shape: string;
            /** Source */
            source: string;
            /** Index Dims */
            index_dims: string[];
            /** Reduce */
            reduce?: string | null;
            /** Unit */
            unit?: string | null;
            /**
             * Censorable
             * @default false
             */
            censorable: boolean;
        };
        /**
         * QuantityScalarRow
         * @description One banded scalar quantity (one row per scenario × stratum cell). A
         *     censorable scalar carries ``p_censored`` (fraction of draws where the event
         *     never fired); a fully-censored cell has ``q* = None`` (no band, only the
         *     count). ``scenario`` is ``as_fitted`` for an old (scenario-less) sidecar.
         */
        QuantityScalarRow: {
            /** Name */
            name: string;
            /**
             * Scenario
             * @default as_fitted
             */
            scenario: string;
            /** Reduce */
            reduce?: string | null;
            /** Source */
            source: string;
            /**
             * Stratum
             * @default {}
             */
            stratum: {
                [key: string]: string;
            };
            /** N Draws */
            n_draws: number;
            /** P Censored */
            p_censored?: number | null;
            /** Q05 */
            q05?: number | null;
            /** Q25 */
            q25?: number | null;
            /** Q50 */
            q50?: number | null;
            /** Q75 */
            q75?: number | null;
            /** Q95 */
            q95?: number | null;
        };
        /**
         * QuantityScalarsResponse
         * @description Every scalar quantity, one row per scenario × stratum cell — the
         *     quantities table. ``scenarios`` is the distinct scenario set (``[]`` when the
         *     fit has no scenario axis).
         */
        QuantityScalarsResponse: {
            /** Run Id */
            run_id: string;
            /** Scenarios */
            scenarios: string[];
            /** Rows */
            rows: components["schemas"]["QuantityScalarRow"][];
        };
        /**
         * QuantitySeriesResponse
         * @description A series quantity's banded trajectory — the ribbon payload. Faceted by
         *     ``stratum`` and overlaid by ``scenario`` on the frontend.
         */
        QuantitySeriesResponse: {
            /** Run Id */
            run_id: string;
            /** Name */
            name: string;
            /** Index Dims */
            index_dims: string[];
            /** Scenarios */
            scenarios: string[];
            /** Points */
            points: components["schemas"]["QuantityBandPoint"][];
        };
        /**
         * RunDetail
         * @description A run's metadata, schema, and verdict — everything but the draws.
         */
        RunDetail: {
            /** Run Id */
            run_id: string;
            /** Label */
            label: string;
            /** Model */
            model: string;
            /** Algorithm */
            algorithm: string;
            /** Backend */
            backend: string;
            /** Status */
            status: string;
            /** N Chains */
            n_chains: number;
            /** Max Iter */
            max_iter?: number | null;
            /** Target Sweeps */
            target_sweeps?: number | null;
            /** Estimated */
            estimated: string[];
            groups: components["schemas"]["ParamGroups"];
            /** Streams */
            streams: components["schemas"]["StreamInfo"][];
            /** Dimensions */
            dimensions: components["schemas"]["DimensionInfo"][];
            /** Findings */
            findings: components["schemas"]["FindingGroup"][];
            /** Available Streams */
            available_streams: string[];
            /**
             * Available Quantities
             * @default []
             */
            available_quantities: components["schemas"]["QuantityInfo"][];
            /**
             * Quantity Scenarios
             * @default []
             */
            quantity_scenarios: string[];
        };
        /**
         * RunSummary
         * @description A run as it appears in the selector list — enough to identify, label, and
         *     badge it without fetching its draws.
         */
        RunSummary: {
            /** Run Id */
            run_id: string;
            /** Label */
            label: string;
            /** Model */
            model: string;
            /** Algorithm */
            algorithm: string;
            /** Backend */
            backend: string;
            /** Status */
            status: string;
            /** N Chains */
            n_chains: number;
            /** N Params */
            n_params: number;
            /** Has Docs */
            has_docs: boolean;
            progress?: components["schemas"]["ProgressInfo"] | null;
            /**
             * Has Prequential
             * @default false
             */
            has_prequential: boolean;
            /** Max Iter */
            max_iter?: number | null;
            /** Updated At */
            updated_at: number;
        };
        /**
         * SourceFile
         * @description One source artifact: syntax-highlighted ``html`` to render and raw
         *     ``text`` for the copy button. ``present`` is false when the file couldn't be
         *     read (e.g. the model moved since the fit).
         */
        SourceFile: {
            /** Path */
            path?: string | null;
            /** Present */
            present: boolean;
            /**
             * Html
             * @default
             */
            html: string;
            /**
             * Text
             * @default
             */
            text: string;
        };
        /**
         * SourceResponse
         * @description The fit's sources: the ``.camdl`` model (read live from its recorded
         *     path) and the ``fit.toml`` (mirrored in the run store). ``highlight_css`` is
         *     the Pygments token stylesheet to inject once.
         */
        SourceResponse: {
            /** Run Id */
            run_id: string;
            model: components["schemas"]["SourceFile"];
            /** Model Identity */
            model_identity?: string | null;
            fit_toml: components["schemas"]["SourceFile"];
            /** Highlight Css */
            highlight_css: string;
        };
        /**
         * StreamInfo
         * @description One observation stream's structure (from the fit's ``schema``).
         */
        StreamInfo: {
            /** Name */
            name: string;
            /** Index Dims */
            index_dims: string[];
            /** Value Kind */
            value_kind?: string | null;
            /** Likelihood */
            likelihood?: string | null;
        };
        /**
         * TraceSeries
         * @description One chain's thinned trace for one parameter: aligned ``iters`` + ``values``.
         */
        TraceSeries: {
            /** Chain */
            chain: number;
            /** Iters */
            iters: number[];
            /** Values */
            values: number[];
        };
        /**
         * TracesResponse
         * @description Per-parameter, per-chain iteration traces (thinned) for the trace grid —
         *     the raw mixing view. ``warmup_cutoff`` marks the retained-tail boundary.
         */
        TracesResponse: {
            /** Run Id */
            run_id: string;
            /** Warmup Cutoff */
            warmup_cutoff: number;
            /** Params */
            params: string[];
            /** Traces */
            traces: components["schemas"]["ParamTrace"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_posterior_api_runs__run_id__posterior_get: {
        parameters: {
            query?: {
                warmup_pct?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosteriorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draws_api_runs__run_id__draws_get: {
        parameters: {
            query?: {
                warmup_pct?: number;
                max_draws?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrawsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_api_runs__run_id__source_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_predictive_api_runs__run_id__predictive__stream__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                stream: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictiveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quantity_series_api_runs__run_id__quantity_series__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuantitySeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quantity_scalars_api_runs__run_id__quantity_scalars_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuantityScalarsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_traces_api_runs__run_id__traces_get: {
        parameters: {
            query?: {
                warmup_pct?: number;
                max_points?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_diagnostics_api_runs__run_id__diagnostics_get: {
        parameters: {
            query?: {
                warmup_pct?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_compare_get: {
        parameters: {
            query: {
                /** @description run ids to compare (≥2) */
                runs: string[];
                baseline?: string | null;
                allow_mismatched_horizon?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
